name: Scrape and Deploy Listings

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  scrape_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update apt-get
        run: sudo apt-get update

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb

      - name: Set up Chrome and Chromedriver
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status
          
          # Debug: Check the installed Chrome version
          google-chrome --version
          
          # Extract the Chrome version and store it in the GITHUB_ENV
          CHROME_VERSION=$(google-chrome --version | grep -oP '\\d+\\.\\d+\\.\\d+')
          echo "CHROME_VERSION=$CHROME_VERSION" >> $GITHUB_ENV
          
          # Debug: Verify the extracted Chrome version
          echo "Extracted Chrome version: $CHROME_VERSION"
          
          # Fetch the appropriate Chromedriver version for the extracted Chrome version
          CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          
          # Debug: Verify the fetched Chromedriver version
          echo "Fetched Chromedriver version: $CHROMEDRIVER_VERSION"
          
          # Download the Chromedriver zip file
          wget -N "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          
          # Unzip the Chromedriver file to /usr/local/bin/
          unzip chromedriver_linux64.zip -d /usr/local/bin/
          
          # Ensure chromedriver is executable
          chmod +x /usr/local/bin/chromedriver
          
          # Debug: Verify the Chromedriver installation
          /usr/local/bin/chromedriver --version
          
      - name: Verify Chromedriver Download
        run: ls -l chromedriver_linux64.zip

      - name: Run scraping script
        run: python scrapingscript.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add listings.db
          git commit -m 'Update listings.db with new scraped data'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
