name: Scrape and Deploy Listings

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  scrape_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update apt-get
        run: sudo apt-get update

      - name: Install Google Chrome
        run: |
          wget https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.141/linux64/chrome-headless-shell-linux64.zip
          unzip chrome-headless-shell-linux64.zip -d chrome
          sudo mv chrome/chrome-headless-shell-linux64/* /usr/local/bin/
          sudo ln -s /usr/local/bin/headless_shell /usr/local/bin/google-chrome

      - name: Install ChromeDriver
        run: |
          wget https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.141/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip -d chromedriver
          sudo mv chromedriver/chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Verify installations
        run: |
          echo "Google Chrome version:"
          google-chrome --version
          echo "ChromeDriver version:"
          chromedriver --version
          echo "Google Chrome directory:"
          which google-chrome
          echo "ChromeDriver directory:"
          which chromedriver

      - name: Run scraping script
        run: python scrapingscript.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add listings.db
          git commit -m 'Update listings.db with new scraped data'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
