name: Scrape and Deploy Listings

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  scrape_and_deploy:
    runs-on: ubuntu-latest
    
    env:
      CHROME_VERSION: '125.0.6422.141'
      CHROMEDRIVER_VERSION: '125.0.6422.141'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Google Chrome
        run: |
          wget https://storage.googleapis.com/chrome-for-testing-public/${{ env.CHROME_VERSION }}/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip -d /usr/local
          rm chrome-linux64.zip
          ln -s /usr/local/chrome-linux64/chrome /usr/bin/google-chrome

      - name: Install ChromeDriver
        run: |
          wget https://storage.googleapis.com/chrome-for-testing-public/${{ env.CHROMEDRIVER_VERSION }}/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip -d /usr/local/bin
          rm chromedriver-linux64.zip

      - name: Verify installations
        run: |
          echo "Google Chrome version:"
          /usr/bin/google-chrome --version
          echo "ChromeDriver version:"
          /usr/local/bin/chromedriver --version

      - name: Run scraping script
        run: python scrapingscript.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add listings.db
          git commit -m 'Update listings.db with new scraped data'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
